version: "3.9"

services:
  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./user_service/.env

  order_service:
    build: ./order_service
    ports:
      - "8001:8000"
    depends_on:
      - order_db
    env_file:
      - ./order_service/.env

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  order_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - user_service
      - order_service
